### ISSUE TITLE
SCSS smart-scale() causes an error in 6.9.0

### ISSUE THREAD

**Issue by aderowbotham** [foundation/foundation-sites#15514]
## What should happen?

It should compile SCSS ➡️ CSS

## What happens instead?

After upgrading an existing project from 6.8.1 to 6.9.0 SCSS compilation fails because `color.channel()` is not a function. 

The "upgrade" was simply a case of changing 6.8.1 to 6.9.0 in **package.json**, then running `npm install` again. But it seems to not be backwards compatible

This is the output:

````
Message:
    node_modules/foundation-sites/scss/util/_color.scss
Error: Undefined function.
    ╷
104 │   @if color.channel($color, "lightness", $space: hsl) > $threshold {
    │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/foundation-sites/scss/util/_color.scss 104:7  smart-scale()
  source/scss/_settings.scss 835:26                          @import
  source/scss/app.scss 4:9                                   root stylesheet
````

## Possible Cause

This seems to be triggered by using smart-scale. `smart-scale()` appears to still exist in **utils/_colour.scss** so it has not been removed. The error appears to come from `color.channel()` being an unknown function, itself called by `smart-scale()`

```
@function smart-scale($color, $scale: 5%, $threshold: 40%) {
  @if color.channel($color, "lightness", $space: hsl) > $threshold {
    $scale: -$scale;
  }
  @return scale-color($color, $lightness: $scale);
} 
```

How to reproduce:
1. npm install
2. run gulp sassBuild as per this gulpfile:

```
const gulp = require('gulp');
const postcss = require('gulp-postcss');
const autoprefixer = require('autoprefixer');
const postCssCustomProperties = require('postcss-custom-properties');
const sass = require('gulp-sass')(require('sass'));
const sourcemaps = require('gulp-sourcemaps');
const concat = require('gulp-concat');

const config = require('./config');

const sassBuild = () => {
  const includePaths = [
    `${config.folders.npm}/foundation-sites/scss`,
    `${config.folders.npm}/motion-ui/src`
  ];

  return gulp.src([`${config.folders.scss}/app.scss`])
    .pipe(sourcemaps.init())
    .pipe(sass({
      includePaths: includePaths,
      outputStyle: 'compressed'
    }).on('error', sass.logError))
    .pipe(postcss([autoprefixer(), postCssCustomProperties()]))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(config.folders.publicCss));
};

````

## Context
It worked fine before upgrading from 6.8.1 to 6.9.0. 

Is there any documentation for migrating a 6.8.x project to 6.9.0 ?
...

## Your Environment

- Foundation version(s) used: 6.9.0
- Device, Operating System and version: macOS
- Node v18.19.0
- npm v10.2.3

**Comment by aderowbotham** [comment]
The cause is that `color.channel()` is a SASS method that was not available in my existing version of sass which was previously 1.66.

To fix it:

1. In **package.json** removed `"sass": "^1.66.0"` and added:

    `"sass-embedded": "^1.79.3",`
    `"sass-true": "^8.0.0",`
    `"sassy-lists": "^3.0.1"`


2. Updated my gulpfile to require **sass-embedded** instead of **sass**

`const sass = require('gulp-sass')(require('sass-embedded'));`

3. Updated my main **app.scss** file to include the following from **foundation.scss**

```
// --- Dependencies ---
@import 'vendor/normalize';
@import '../_vendor/sassy-lists/stylesheets/helpers/missing-dependencies';
@import '../_vendor/sassy-lists/stylesheets/helpers/true';
@import '../_vendor/sassy-lists/stylesheets/functions/contain';
@import '../_vendor/sassy-lists/stylesheets/functions/purge';
@import '../_vendor/sassy-lists/stylesheets/functions/remove';
@import '../_vendor/sassy-lists/stylesheets/functions/replace';
@import '../_vendor/sassy-lists/stylesheets/functions/to-list';

// --- Components ---
@import 'util/util';
// Global styles
@import 'global';
@import 'forms/forms';
@import 'typography/typography';
```

--- 

Now it compiles. 

The only issue is very verbose deprecation warnings such as this:


```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> ../../../foundation-sites/scss/forms/_select.scss
46  │       padding-#{$global-right}: ($form-spacing * 1.5);
    │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   
 ```

**Comment by lalo-mx** [comment]
Using Angular CLI you can solve the issue by adding overrides in package.json, for example:

```

  "overrides": {
    "@angular-devkit/build-angular":  {
      "sass": "~1.79.3"
    },
    "@angular-devkit/build": {
      "sass": "~1.79.3"
    }
  },
```

**Comment by ali-ic** [comment]
@lalo-mx thank you so much! I looked at the suggested solution a couple days ago but it wasn't suitable for Angular. And I randomly checked again today and you had posted a solution 3h ago! And it worked! Thanks a ton!
