### PR TITLE
use on() to listen for the load event

### PR DESCRIPTION
**Pull request by DanielRuf**
`.load()` is deprecated since jQuery 1.8 and the event can only be fetched with `.on('load')`

> Note: Prior to jQuery 3.0, the event handling suite also had a method named .load(). Older versions of jQuery determined which method to fire based on the set of arguments passed to it.

https://api.jquery.com/load/
https://api.jquery.com/load-event/

### CODE REVIEW

**Review by DaSchTour — APPROVED** [review]
Looks good

**Review by ncoden — APPROVED** [review]

**Comment by DanielRuf** [comment]
In the source files there are two components which use the old syntax. You can see the direct changes at https://github.com/zurb/foundation-sites/pull/10729/files

**Comment by rainzetroc** [comment]
i check every function and manually look for the .load. quite hard to find, then finally the widget is working fine now, made it work with version 3.3.1 :D 
im not sure about your question of what version of foundation sites, but im using npm. i cant show you the exact error since it contains some details. but i can show you list of error shown in console. 

Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught TypeError: Cannot read property 'pointerType' of undefined
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught TypeError: Cannot read property 'en' of undefined
(Then the console of my widget show)
Uncaught TypeError: resCont.truncate is not a function
Uncaught TypeError: Cannot read property 'left' of undefined

**Comment by DanielRuf** [comment]
> Failed to load resource: the server responded with a status of 404 (Not Found)
> Uncaught TypeError: Cannot read property 'pointerType' of undefined
> Failed to load resource: the server responded with a status of 404 (Not Found)
> Uncaught TypeError: Cannot read property 'en' of undefined
> (Then the console of my widget show)
> Uncaught TypeError: resCont.truncate is not a function
> Uncaught TypeError: Cannot read property 'left' of undefined

These are all unrelated to the issue.
404s mean that a file can not be found on your server (the URL is probably wrong).
Also something accesses `.pointerType` but the text before it is undefined (you can click on the line number in the console on the right side).
Same for something `.en`, `.left` and `.truncate()` is not a function on `resCont`.

Generally I also provide free mentoring (if this is a freetime project that you are working on and nothing from your workplace) where I help people to understand how they can solve issues in their projects and son on.

Let me know if you need any help in regard of this (only freetime projects).

Otherwise, the exact error messages are always helpful.

The error which points to the `load` problem would be `TypeError: url.indexOf is not a function`.

See https://github.com/zurb/foundation-sites/issues/10096

**Comment by rainzetroc** [comment]
Thanks a lot, actually this is work related. this is part of my story. i would love to learn more since im a newbie, and its my firstime to use this one. react /redux is our main tech and i can rate myself for 1/10 haha i would love to read more helpful stuffs you will share to improve my programming skills.

**Comment by DanielRuf** [comment]
If you are interested, I can invite you. You just have to join https://gitter.im with your GitHub login.

**Comment by rainzetroc** [comment]
sure please im interested.im not so familiar how to use that do you have social media account?

**Comment by DanielRuf** [comment]
@rainzetroc I've sent you the links on Gitter to our channels for Foundation.
